name: electronil
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: electronil
  id: 17d8094e-ddfb-4032-83e4-771bdf4a36d2
  # Optionally activate xdebug
  xdebug: true
  conf: config/php.ini
  
  
services:

# Override the appsever to add some environment variables and install an extra VIM package
  appserver:
    extras:
      - apt-get update -y
      - apt-get install vim -y

# Add a lando vim command
tooling:
  vim:
    service: appserver

